/* This code was generated by Usuba.
   See https://github.com/DadaIsCrazy/usuba.
   From the file "../FAME-Usuba/panteas_trick/aesround.ua" (included below). */

//#include <stdint.h>

/* Do NOT change the order of those define/include */
#define NO_RUNTIME
#ifndef BITS_PER_REG
#define BITS_PER_REG 32
#endif
/* including the architecture specific .h */
#include "FAME.h"


/* auxiliary functions */
static void SubBytes_single__ (/*inputs*/ DATATYPE U0,DATATYPE U1,DATATYPE U2,DATATYPE U3,DATATYPE U4,DATATYPE U5,DATATYPE U6,DATATYPE U7, /*outputs*/ DATATYPE* S0,DATATYPE* S1,DATATYPE* S2,DATATYPE* S3,DATATYPE* S4,DATATYPE* S5,DATATYPE* S6,DATATYPE* S7) {

  // Variables declaration
  DATATYPE _tmp1_;
  DATATYPE _tmp2_;
  DATATYPE _tmp3_;
  DATATYPE _tmp4_;
  DATATYPE t0;
  DATATYPE t1;
  DATATYPE t10;
  DATATYPE t11;
  DATATYPE t12;
  DATATYPE t13;
  DATATYPE t14;
  DATATYPE t15;
  DATATYPE t16;
  DATATYPE t17;
  DATATYPE t18;
  DATATYPE t19;
  DATATYPE t2;
  DATATYPE t20;
  DATATYPE t21;
  DATATYPE t22;
  DATATYPE t23;
  DATATYPE t24;
  DATATYPE t25;
  DATATYPE t26;
  DATATYPE t27;
  DATATYPE t28;
  DATATYPE t29;
  DATATYPE t3;
  DATATYPE t30;
  DATATYPE t31;
  DATATYPE t32;
  DATATYPE t33;
  DATATYPE t34;
  DATATYPE t35;
  DATATYPE t36;
  DATATYPE t37;
  DATATYPE t38;
  DATATYPE t39;
  DATATYPE t4;
  DATATYPE t40;
  DATATYPE t41;
  DATATYPE t42;
  DATATYPE t43;
  DATATYPE t44;
  DATATYPE t45;
  DATATYPE t5;
  DATATYPE t6;
  DATATYPE t7;
  DATATYPE t8;
  DATATYPE t9;
  DATATYPE tc1;
  DATATYPE tc10;
  DATATYPE tc11;
  DATATYPE tc12;
  DATATYPE tc13;
  DATATYPE tc14;
  DATATYPE tc16;
  DATATYPE tc17;
  DATATYPE tc18;
  DATATYPE tc2;
  DATATYPE tc20;
  DATATYPE tc21;
  DATATYPE tc26;
  DATATYPE tc3;
  DATATYPE tc4;
  DATATYPE tc5;
  DATATYPE tc6;
  DATATYPE tc7;
  DATATYPE tc8;
  DATATYPE tc9;
  DATATYPE y1;
  DATATYPE y10;
  DATATYPE y11;
  DATATYPE y12;
  DATATYPE y13;
  DATATYPE y14;
  DATATYPE y15;
  DATATYPE y16;
  DATATYPE y17;
  DATATYPE y18;
  DATATYPE y19;
  DATATYPE y2;
  DATATYPE y20;
  DATATYPE y21;
  DATATYPE y3;
  DATATYPE y4;
  DATATYPE y5;
  DATATYPE y6;
  DATATYPE y7;
  DATATYPE y8;
  DATATYPE y9;
  DATATYPE z0;
  DATATYPE z1;
  DATATYPE z10;
  DATATYPE z11;
  DATATYPE z12;
  DATATYPE z13;
  DATATYPE z14;
  DATATYPE z15;
  DATATYPE z16;
  DATATYPE z17;
  DATATYPE z2;
  DATATYPE z3;
  DATATYPE z4;
  DATATYPE z5;
  DATATYPE z6;
  DATATYPE z7;
  DATATYPE z8;
  DATATYPE z9;

  // Instructions (body)
  XOR(y14,U3,U5);
  XOR(y13,U0,U6);
  XOR(y9,U0,U3);
  XOR(y8,U0,U5);
  XOR(t0,U1,U2);
  XOR(y1,t0,U7);
  XOR(y4,y1,U3);
  XOR(y12,y13,y14);
  XOR(y2,y1,U0);
  XOR(y5,y1,U6);
  XOR(y3,y5,y8);
  XOR(t1,U4,y12);
  XOR(y15,t1,U5);
  XOR(y20,t1,U1);
  XOR(y6,y15,U7);
  XOR(y10,y15,t0);
  XOR(y11,y20,y9);
  XOR(y7,U7,y11);
  XOR(y17,y10,y11);
  XOR(y19,y10,y8);
  XOR(y16,t0,y11);
  XOR(y21,y13,y16);
  XOR(y18,U0,y16);
  AND(t2,y12,y15);
  AND(t3,y3,y6);
  XOR(t4,t3,t2);
  AND(t5,y4,U7);
  XOR(t6,t5,t2);
  AND(t7,y13,y16);
  AND(t8,y5,y1);
  XOR(t9,t8,t7);
  AND(t10,y2,y7);
  XOR(t11,t10,t7);
  AND(t12,y9,y11);
  AND(t13,y14,y17);
  XOR(t14,t13,t12);
  AND(t15,y8,y10);
  XOR(t16,t15,t12);
  XOR(t17,t4,y20);
  XOR(t18,t6,t16);
  XOR(t19,t9,t14);
  XOR(t20,t11,t16);
  XOR(t21,t17,t14);
  XOR(t22,t18,y19);
  XOR(t23,t19,y21);
  XOR(t24,t20,y18);
  XOR(t25,t21,t22);
  AND(t26,t21,t23);
  XOR(t27,t24,t26);
  AND(t28,t25,t27);
  XOR(t29,t28,t22);
  XOR(t30,t23,t24);
  XOR(t31,t22,t26);
  AND(t32,t31,t30);
  XOR(t33,t32,t24);
  XOR(t34,t23,t33);
  XOR(t35,t27,t33);
  AND(t36,t24,t35);
  XOR(t37,t36,t34);
  XOR(t38,t27,t36);
  AND(t39,t29,t38);
  XOR(t40,t25,t39);
  XOR(t41,t40,t37);
  XOR(t42,t29,t33);
  XOR(t43,t29,t40);
  XOR(t44,t33,t37);
  XOR(t45,t42,t41);
  AND(z0,t44,y15);
  AND(z1,t37,y6);
  AND(z2,t33,U7);
  AND(z3,t43,y16);
  AND(z4,t40,y1);
  AND(z5,t29,y7);
  AND(z6,t42,y11);
  AND(z7,t45,y17);
  AND(z8,t41,y10);
  AND(z9,t44,y12);
  AND(z10,t37,y3);
  AND(z11,t33,y4);
  AND(z12,t43,y13);
  AND(z13,t40,y5);
  AND(z14,t29,y2);
  AND(z15,t42,y9);
  AND(z16,t45,y14);
  AND(z17,t41,y8);
  XOR(tc1,z15,z16);
  XOR(tc2,z10,tc1);
  XOR(tc3,z9,tc2);
  XOR(tc4,z0,z2);
  XOR(tc5,z1,z0);
  XOR(tc6,z3,z4);
  XOR(tc7,z12,tc4);
  XOR(tc8,z7,tc6);
  XOR(tc9,z8,tc7);
  XOR(tc10,tc8,tc9);
  XOR(tc11,tc6,tc5);
  XOR(tc12,z3,z5);
  XOR(tc13,z13,tc1);
  XOR(tc14,tc4,tc12);
  XOR(*S3,tc3,tc11);
  XOR(tc16,z6,tc8);
  XOR(tc17,z14,tc10);
  XOR(tc18,tc13,tc14);
  XOR(_tmp1_,z12,tc18);
  NOT(*S7,_tmp1_);
  XOR(tc20,z15,tc16);
  XOR(tc21,tc2,z11);
  XOR(*S0,tc3,tc16);
  XOR(_tmp2_,tc10,tc18);
  NOT(*S6,_tmp2_);
  XOR(*S4,tc14,*S3);
  XOR(_tmp3_,*S3,tc16);
  NOT(*S1,_tmp3_);
  XOR(tc26,tc17,tc20);
  XOR(_tmp4_,tc26,z17);
  NOT(*S2,_tmp4_);
  XOR(*S5,tc21,tc17);

}

static void SubBytes__ (/*inputs*/ DATATYPE inputSB__[128], /*outputs*/ DATATYPE out__[128]) {
  
  // Variables declaration
  ;

  // Instructions (body)
  for (int i__ = 0; i__ <= 15; i__++) {
    SubBytes_single__(inputSB__[((i__ * 8) + 0)],inputSB__[((i__ * 8) + 1)],inputSB__[((i__ * 8) + 2)],inputSB__[((i__ * 8) + 3)],inputSB__[((i__ * 8) + 4)],inputSB__[((i__ * 8) + 5)],inputSB__[((i__ * 8) + 6)],inputSB__[((i__ * 8) + 7)],&out__[((i__ * 8) + 0)],&out__[((i__ * 8) + 1)],&out__[((i__ * 8) + 2)],&out__[((i__ * 8) + 3)],&out__[((i__ * 8) + 4)],&out__[((i__ * 8) + 5)],&out__[((i__ * 8) + 6)],&out__[((i__ * 8) + 7)]);
  }

}

static void ShiftRows__ (/*inputs*/ DATATYPE inputSR__[128], /*outputs*/ DATATYPE output__[128]) {
  
  // Variables declaration
  ;

  // Instructions (body)
  output__[0] = inputSR__[0];
  output__[1] = inputSR__[1];
  output__[2] = inputSR__[2];
  output__[3] = inputSR__[3];
  output__[4] = inputSR__[4];
  output__[5] = inputSR__[5];
  output__[6] = inputSR__[6];
  output__[7] = inputSR__[7];
  output__[8] = inputSR__[40];
  output__[9] = inputSR__[41];
  output__[10] = inputSR__[42];
  output__[11] = inputSR__[43];
  output__[12] = inputSR__[44];
  output__[13] = inputSR__[45];
  output__[14] = inputSR__[46];
  output__[15] = inputSR__[47];
  output__[16] = inputSR__[80];
  output__[17] = inputSR__[81];
  output__[18] = inputSR__[82];
  output__[19] = inputSR__[83];
  output__[20] = inputSR__[84];
  output__[21] = inputSR__[85];
  output__[22] = inputSR__[86];
  output__[23] = inputSR__[87];
  output__[24] = inputSR__[120];
  output__[25] = inputSR__[121];
  output__[26] = inputSR__[122];
  output__[27] = inputSR__[123];
  output__[28] = inputSR__[124];
  output__[29] = inputSR__[125];
  output__[30] = inputSR__[126];
  output__[31] = inputSR__[127];
  output__[32] = inputSR__[32];
  output__[33] = inputSR__[33];
  output__[34] = inputSR__[34];
  output__[35] = inputSR__[35];
  output__[36] = inputSR__[36];
  output__[37] = inputSR__[37];
  output__[38] = inputSR__[38];
  output__[39] = inputSR__[39];
  output__[40] = inputSR__[72];
  output__[41] = inputSR__[73];
  output__[42] = inputSR__[74];
  output__[43] = inputSR__[75];
  output__[44] = inputSR__[76];
  output__[45] = inputSR__[77];
  output__[46] = inputSR__[78];
  output__[47] = inputSR__[79];
  output__[48] = inputSR__[112];
  output__[49] = inputSR__[113];
  output__[50] = inputSR__[114];
  output__[51] = inputSR__[115];
  output__[52] = inputSR__[116];
  output__[53] = inputSR__[117];
  output__[54] = inputSR__[118];
  output__[55] = inputSR__[119];
  output__[56] = inputSR__[24];
  output__[57] = inputSR__[25];
  output__[58] = inputSR__[26];
  output__[59] = inputSR__[27];
  output__[60] = inputSR__[28];
  output__[61] = inputSR__[29];
  output__[62] = inputSR__[30];
  output__[63] = inputSR__[31];
  output__[64] = inputSR__[64];
  output__[65] = inputSR__[65];
  output__[66] = inputSR__[66];
  output__[67] = inputSR__[67];
  output__[68] = inputSR__[68];
  output__[69] = inputSR__[69];
  output__[70] = inputSR__[70];
  output__[71] = inputSR__[71];
  output__[72] = inputSR__[104];
  output__[73] = inputSR__[105];
  output__[74] = inputSR__[106];
  output__[75] = inputSR__[107];
  output__[76] = inputSR__[108];
  output__[77] = inputSR__[109];
  output__[78] = inputSR__[110];
  output__[79] = inputSR__[111];
  output__[80] = inputSR__[16];
  output__[81] = inputSR__[17];
  output__[82] = inputSR__[18];
  output__[83] = inputSR__[19];
  output__[84] = inputSR__[20];
  output__[85] = inputSR__[21];
  output__[86] = inputSR__[22];
  output__[87] = inputSR__[23];
  output__[88] = inputSR__[56];
  output__[89] = inputSR__[57];
  output__[90] = inputSR__[58];
  output__[91] = inputSR__[59];
  output__[92] = inputSR__[60];
  output__[93] = inputSR__[61];
  output__[94] = inputSR__[62];
  output__[95] = inputSR__[63];
  output__[96] = inputSR__[96];
  output__[97] = inputSR__[97];
  output__[98] = inputSR__[98];
  output__[99] = inputSR__[99];
  output__[100] = inputSR__[100];
  output__[101] = inputSR__[101];
  output__[102] = inputSR__[102];
  output__[103] = inputSR__[103];
  output__[104] = inputSR__[8];
  output__[105] = inputSR__[9];
  output__[106] = inputSR__[10];
  output__[107] = inputSR__[11];
  output__[108] = inputSR__[12];
  output__[109] = inputSR__[13];
  output__[110] = inputSR__[14];
  output__[111] = inputSR__[15];
  output__[112] = inputSR__[48];
  output__[113] = inputSR__[49];
  output__[114] = inputSR__[50];
  output__[115] = inputSR__[51];
  output__[116] = inputSR__[52];
  output__[117] = inputSR__[53];
  output__[118] = inputSR__[54];
  output__[119] = inputSR__[55];
  output__[120] = inputSR__[88];
  output__[121] = inputSR__[89];
  output__[122] = inputSR__[90];
  output__[123] = inputSR__[91];
  output__[124] = inputSR__[92];
  output__[125] = inputSR__[93];
  output__[126] = inputSR__[94];
  output__[127] = inputSR__[95];

}

static void MixColumn__ (/*inputs*/ DATATYPE inp__[128], /*outputs*/ DATATYPE out__[128]) {
  
  // Variables declaration
  DATATYPE MixColumn_single___1__tmp10_[8];
  DATATYPE MixColumn_single___1__tmp11_[8];
  DATATYPE MixColumn_single___1__tmp12_[8];
  DATATYPE MixColumn_single___1__tmp13_[8];
  DATATYPE MixColumn_single___1__tmp14_[8];
  DATATYPE MixColumn_single___1__tmp15_[8];
  DATATYPE MixColumn_single___1__tmp16_[8];
  DATATYPE MixColumn_single___1__tmp17_[8];
  DATATYPE MixColumn_single___1__tmp18_[8];
  DATATYPE MixColumn_single___1__tmp19_[8];
  DATATYPE MixColumn_single___1__tmp20_[8];
  DATATYPE MixColumn_single___1__tmp21_[8];
  DATATYPE MixColumn_single___1__tmp22_[8];
  DATATYPE MixColumn_single___1__tmp7_[8];
  DATATYPE MixColumn_single___1__tmp8_[8];
  DATATYPE MixColumn_single___1__tmp9_[8];
  DATATYPE MixColumn_single___1_times2___1__tmp5_[8];
  DATATYPE MixColumn_single___1_times2___2__tmp5_[8];
  DATATYPE MixColumn_single___1_times2___3__tmp5_[8];
  DATATYPE MixColumn_single___1_times2___4__tmp5_[8];
  DATATYPE MixColumn_single___1_times3___1__tmp6_[8];
  DATATYPE MixColumn_single___1_times3___1_times2___1__tmp5_[8];
  DATATYPE MixColumn_single___1_times3___2__tmp6_[8];
  DATATYPE MixColumn_single___1_times3___2_times2___1__tmp5_[8];
  DATATYPE MixColumn_single___1_times3___3__tmp6_[8];
  DATATYPE MixColumn_single___1_times3___3_times2___1__tmp5_[8];
  DATATYPE MixColumn_single___1_times3___4__tmp6_[8];
  DATATYPE MixColumn_single___1_times3___4_times2___1__tmp5_[8];

  // Instructions (body)
  for (int i__ = 0; i__ <= 3; i__++) {
    MixColumn_single___1_times2___1__tmp5_[0] = inp__[((i__ * 32) + 1)];
    MixColumn_single___1_times2___1__tmp5_[1] = inp__[((i__ * 32) + 2)];
    MixColumn_single___1_times2___1__tmp5_[2] = inp__[((i__ * 32) + 3)];
    MixColumn_single___1_times2___1__tmp5_[3] = inp__[((i__ * 32) + 4)];
    MixColumn_single___1_times2___1__tmp5_[4] = inp__[((i__ * 32) + 5)];
    MixColumn_single___1_times2___1__tmp5_[5] = inp__[((i__ * 32) + 6)];
    MixColumn_single___1_times2___1__tmp5_[6] = inp__[((i__ * 32) + 7)];
    MixColumn_single___1_times2___1__tmp5_[7] = SET_ALL_ONE();
    MixColumn_single___1__tmp7_[0] = MixColumn_single___1_times2___1__tmp5_[0];
    MixColumn_single___1__tmp7_[1] = MixColumn_single___1_times2___1__tmp5_[1];
    MixColumn_single___1__tmp7_[2] = MixColumn_single___1_times2___1__tmp5_[2];
    XOR(MixColumn_single___1__tmp7_[3],MixColumn_single___1_times2___1__tmp5_[3],inp__[((i__ * 32) + 0)]);
    XOR(MixColumn_single___1__tmp7_[4],MixColumn_single___1_times2___1__tmp5_[4],inp__[((i__ * 32) + 0)]);
    MixColumn_single___1__tmp7_[5] = MixColumn_single___1_times2___1__tmp5_[5];
    XOR(MixColumn_single___1__tmp7_[6],MixColumn_single___1_times2___1__tmp5_[6],inp__[((i__ * 32) + 0)]);
    XOR(MixColumn_single___1__tmp7_[7],MixColumn_single___1_times2___1__tmp5_[7],inp__[((i__ * 32) + 0)]);
    MixColumn_single___1_times3___1_times2___1__tmp5_[0] = inp__[((i__ * 32) + 9)];
    MixColumn_single___1_times3___1_times2___1__tmp5_[1] = inp__[((i__ * 32) + 10)];
    MixColumn_single___1_times3___1_times2___1__tmp5_[2] = inp__[((i__ * 32) + 11)];
    MixColumn_single___1_times3___1_times2___1__tmp5_[3] = inp__[((i__ * 32) + 12)];
    MixColumn_single___1_times3___1_times2___1__tmp5_[4] = inp__[((i__ * 32) + 13)];
    MixColumn_single___1_times3___1_times2___1__tmp5_[5] = inp__[((i__ * 32) + 14)];
    MixColumn_single___1_times3___1_times2___1__tmp5_[6] = inp__[((i__ * 32) + 15)];
    MixColumn_single___1_times3___1_times2___1__tmp5_[7] = SET_ALL_ONE();
    MixColumn_single___1_times3___1__tmp6_[0] = MixColumn_single___1_times3___1_times2___1__tmp5_[0];
    MixColumn_single___1_times3___1__tmp6_[1] = MixColumn_single___1_times3___1_times2___1__tmp5_[1];
    MixColumn_single___1_times3___1__tmp6_[2] = MixColumn_single___1_times3___1_times2___1__tmp5_[2];
    XOR(MixColumn_single___1_times3___1__tmp6_[3],MixColumn_single___1_times3___1_times2___1__tmp5_[3],inp__[((i__ * 32) + 8)]);
    XOR(MixColumn_single___1_times3___1__tmp6_[4],MixColumn_single___1_times3___1_times2___1__tmp5_[4],inp__[((i__ * 32) + 8)]);
    MixColumn_single___1_times3___1__tmp6_[5] = MixColumn_single___1_times3___1_times2___1__tmp5_[5];
    XOR(MixColumn_single___1_times3___1__tmp6_[6],MixColumn_single___1_times3___1_times2___1__tmp5_[6],inp__[((i__ * 32) + 8)]);
    XOR(MixColumn_single___1_times3___1__tmp6_[7],MixColumn_single___1_times3___1_times2___1__tmp5_[7],inp__[((i__ * 32) + 8)]);
    XOR(MixColumn_single___1__tmp8_[0],MixColumn_single___1_times3___1__tmp6_[0],inp__[((i__ * 32) + 8)]);
    XOR(MixColumn_single___1__tmp8_[1],MixColumn_single___1_times3___1__tmp6_[1],inp__[((i__ * 32) + 9)]);
    XOR(MixColumn_single___1__tmp8_[2],MixColumn_single___1_times3___1__tmp6_[2],inp__[((i__ * 32) + 10)]);
    XOR(MixColumn_single___1__tmp8_[3],MixColumn_single___1_times3___1__tmp6_[3],inp__[((i__ * 32) + 11)]);
    XOR(MixColumn_single___1__tmp8_[4],MixColumn_single___1_times3___1__tmp6_[4],inp__[((i__ * 32) + 12)]);
    XOR(MixColumn_single___1__tmp8_[5],MixColumn_single___1_times3___1__tmp6_[5],inp__[((i__ * 32) + 13)]);
    XOR(MixColumn_single___1__tmp8_[6],MixColumn_single___1_times3___1__tmp6_[6],inp__[((i__ * 32) + 14)]);
    XOR(MixColumn_single___1__tmp8_[7],MixColumn_single___1_times3___1__tmp6_[7],inp__[((i__ * 32) + 15)]);
    XOR(MixColumn_single___1__tmp9_[0],MixColumn_single___1__tmp7_[0],MixColumn_single___1__tmp8_[0]);
    XOR(MixColumn_single___1__tmp9_[1],MixColumn_single___1__tmp7_[1],MixColumn_single___1__tmp8_[1]);
    XOR(MixColumn_single___1__tmp9_[2],MixColumn_single___1__tmp7_[2],MixColumn_single___1__tmp8_[2]);
    XOR(MixColumn_single___1__tmp9_[3],MixColumn_single___1__tmp7_[3],MixColumn_single___1__tmp8_[3]);
    XOR(MixColumn_single___1__tmp9_[4],MixColumn_single___1__tmp7_[4],MixColumn_single___1__tmp8_[4]);
    XOR(MixColumn_single___1__tmp9_[5],MixColumn_single___1__tmp7_[5],MixColumn_single___1__tmp8_[5]);
    XOR(MixColumn_single___1__tmp9_[6],MixColumn_single___1__tmp7_[6],MixColumn_single___1__tmp8_[6]);
    XOR(MixColumn_single___1__tmp9_[7],MixColumn_single___1__tmp7_[7],MixColumn_single___1__tmp8_[7]);
    XOR(MixColumn_single___1__tmp10_[0],MixColumn_single___1__tmp9_[0],inp__[((i__ * 32) + 16)]);
    XOR(MixColumn_single___1__tmp10_[1],MixColumn_single___1__tmp9_[1],inp__[((i__ * 32) + 17)]);
    XOR(MixColumn_single___1__tmp10_[2],MixColumn_single___1__tmp9_[2],inp__[((i__ * 32) + 18)]);
    XOR(MixColumn_single___1__tmp10_[3],MixColumn_single___1__tmp9_[3],inp__[((i__ * 32) + 19)]);
    XOR(MixColumn_single___1__tmp10_[4],MixColumn_single___1__tmp9_[4],inp__[((i__ * 32) + 20)]);
    XOR(MixColumn_single___1__tmp10_[5],MixColumn_single___1__tmp9_[5],inp__[((i__ * 32) + 21)]);
    XOR(MixColumn_single___1__tmp10_[6],MixColumn_single___1__tmp9_[6],inp__[((i__ * 32) + 22)]);
    XOR(MixColumn_single___1__tmp10_[7],MixColumn_single___1__tmp9_[7],inp__[((i__ * 32) + 23)]);
    XOR(out__[((i__ * 32) + 0)],MixColumn_single___1__tmp10_[0],inp__[((i__ * 32) + 24)]);
    XOR(out__[((i__ * 32) + 1)],MixColumn_single___1__tmp10_[1],inp__[((i__ * 32) + 25)]);
    XOR(out__[((i__ * 32) + 2)],MixColumn_single___1__tmp10_[2],inp__[((i__ * 32) + 26)]);
    XOR(out__[((i__ * 32) + 3)],MixColumn_single___1__tmp10_[3],inp__[((i__ * 32) + 27)]);
    XOR(out__[((i__ * 32) + 4)],MixColumn_single___1__tmp10_[4],inp__[((i__ * 32) + 28)]);
    XOR(out__[((i__ * 32) + 5)],MixColumn_single___1__tmp10_[5],inp__[((i__ * 32) + 29)]);
    XOR(out__[((i__ * 32) + 6)],MixColumn_single___1__tmp10_[6],inp__[((i__ * 32) + 30)]);
    XOR(out__[((i__ * 32) + 7)],MixColumn_single___1__tmp10_[7],inp__[((i__ * 32) + 31)]);
    MixColumn_single___1_times2___2__tmp5_[0] = inp__[((i__ * 32) + 9)];
    MixColumn_single___1_times2___2__tmp5_[1] = inp__[((i__ * 32) + 10)];
    MixColumn_single___1_times2___2__tmp5_[2] = inp__[((i__ * 32) + 11)];
    MixColumn_single___1_times2___2__tmp5_[3] = inp__[((i__ * 32) + 12)];
    MixColumn_single___1_times2___2__tmp5_[4] = inp__[((i__ * 32) + 13)];
    MixColumn_single___1_times2___2__tmp5_[5] = inp__[((i__ * 32) + 14)];
    MixColumn_single___1_times2___2__tmp5_[6] = inp__[((i__ * 32) + 15)];
    MixColumn_single___1_times2___2__tmp5_[7] = SET_ALL_ONE();
    MixColumn_single___1__tmp11_[0] = MixColumn_single___1_times2___2__tmp5_[0];
    MixColumn_single___1__tmp11_[1] = MixColumn_single___1_times2___2__tmp5_[1];
    MixColumn_single___1__tmp11_[2] = MixColumn_single___1_times2___2__tmp5_[2];
    XOR(MixColumn_single___1__tmp11_[3],MixColumn_single___1_times2___2__tmp5_[3],inp__[((i__ * 32) + 8)]);
    XOR(MixColumn_single___1__tmp11_[4],MixColumn_single___1_times2___2__tmp5_[4],inp__[((i__ * 32) + 8)]);
    MixColumn_single___1__tmp11_[5] = MixColumn_single___1_times2___2__tmp5_[5];
    XOR(MixColumn_single___1__tmp11_[6],MixColumn_single___1_times2___2__tmp5_[6],inp__[((i__ * 32) + 8)]);
    XOR(MixColumn_single___1__tmp11_[7],MixColumn_single___1_times2___2__tmp5_[7],inp__[((i__ * 32) + 8)]);
    XOR(MixColumn_single___1__tmp12_[0],inp__[((i__ * 32) + 0)],MixColumn_single___1__tmp11_[0]);
    XOR(MixColumn_single___1__tmp12_[1],inp__[((i__ * 32) + 1)],MixColumn_single___1__tmp11_[1]);
    XOR(MixColumn_single___1__tmp12_[2],inp__[((i__ * 32) + 2)],MixColumn_single___1__tmp11_[2]);
    XOR(MixColumn_single___1__tmp12_[3],inp__[((i__ * 32) + 3)],MixColumn_single___1__tmp11_[3]);
    XOR(MixColumn_single___1__tmp12_[4],inp__[((i__ * 32) + 4)],MixColumn_single___1__tmp11_[4]);
    XOR(MixColumn_single___1__tmp12_[5],inp__[((i__ * 32) + 5)],MixColumn_single___1__tmp11_[5]);
    XOR(MixColumn_single___1__tmp12_[6],inp__[((i__ * 32) + 6)],MixColumn_single___1__tmp11_[6]);
    XOR(MixColumn_single___1__tmp12_[7],inp__[((i__ * 32) + 7)],MixColumn_single___1__tmp11_[7]);
    MixColumn_single___1_times3___2_times2___1__tmp5_[0] = inp__[((i__ * 32) + 17)];
    MixColumn_single___1_times3___2_times2___1__tmp5_[1] = inp__[((i__ * 32) + 18)];
    MixColumn_single___1_times3___2_times2___1__tmp5_[2] = inp__[((i__ * 32) + 19)];
    MixColumn_single___1_times3___2_times2___1__tmp5_[3] = inp__[((i__ * 32) + 20)];
    MixColumn_single___1_times3___2_times2___1__tmp5_[4] = inp__[((i__ * 32) + 21)];
    MixColumn_single___1_times3___2_times2___1__tmp5_[5] = inp__[((i__ * 32) + 22)];
    MixColumn_single___1_times3___2_times2___1__tmp5_[6] = inp__[((i__ * 32) + 23)];
    MixColumn_single___1_times3___2_times2___1__tmp5_[7] = SET_ALL_ONE();
    MixColumn_single___1_times3___2__tmp6_[0] = MixColumn_single___1_times3___2_times2___1__tmp5_[0];
    MixColumn_single___1_times3___2__tmp6_[1] = MixColumn_single___1_times3___2_times2___1__tmp5_[1];
    MixColumn_single___1_times3___2__tmp6_[2] = MixColumn_single___1_times3___2_times2___1__tmp5_[2];
    XOR(MixColumn_single___1_times3___2__tmp6_[3],MixColumn_single___1_times3___2_times2___1__tmp5_[3],inp__[((i__ * 32) + 16)]);
    XOR(MixColumn_single___1_times3___2__tmp6_[4],MixColumn_single___1_times3___2_times2___1__tmp5_[4],inp__[((i__ * 32) + 16)]);
    MixColumn_single___1_times3___2__tmp6_[5] = MixColumn_single___1_times3___2_times2___1__tmp5_[5];
    XOR(MixColumn_single___1_times3___2__tmp6_[6],MixColumn_single___1_times3___2_times2___1__tmp5_[6],inp__[((i__ * 32) + 16)]);
    XOR(MixColumn_single___1_times3___2__tmp6_[7],MixColumn_single___1_times3___2_times2___1__tmp5_[7],inp__[((i__ * 32) + 16)]);
    XOR(MixColumn_single___1__tmp13_[0],MixColumn_single___1_times3___2__tmp6_[0],inp__[((i__ * 32) + 16)]);
    XOR(MixColumn_single___1__tmp13_[1],MixColumn_single___1_times3___2__tmp6_[1],inp__[((i__ * 32) + 17)]);
    XOR(MixColumn_single___1__tmp13_[2],MixColumn_single___1_times3___2__tmp6_[2],inp__[((i__ * 32) + 18)]);
    XOR(MixColumn_single___1__tmp13_[3],MixColumn_single___1_times3___2__tmp6_[3],inp__[((i__ * 32) + 19)]);
    XOR(MixColumn_single___1__tmp13_[4],MixColumn_single___1_times3___2__tmp6_[4],inp__[((i__ * 32) + 20)]);
    XOR(MixColumn_single___1__tmp13_[5],MixColumn_single___1_times3___2__tmp6_[5],inp__[((i__ * 32) + 21)]);
    XOR(MixColumn_single___1__tmp13_[6],MixColumn_single___1_times3___2__tmp6_[6],inp__[((i__ * 32) + 22)]);
    XOR(MixColumn_single___1__tmp13_[7],MixColumn_single___1_times3___2__tmp6_[7],inp__[((i__ * 32) + 23)]);
    XOR(MixColumn_single___1__tmp14_[0],MixColumn_single___1__tmp12_[0],MixColumn_single___1__tmp13_[0]);
    XOR(MixColumn_single___1__tmp14_[1],MixColumn_single___1__tmp12_[1],MixColumn_single___1__tmp13_[1]);
    XOR(MixColumn_single___1__tmp14_[2],MixColumn_single___1__tmp12_[2],MixColumn_single___1__tmp13_[2]);
    XOR(MixColumn_single___1__tmp14_[3],MixColumn_single___1__tmp12_[3],MixColumn_single___1__tmp13_[3]);
    XOR(MixColumn_single___1__tmp14_[4],MixColumn_single___1__tmp12_[4],MixColumn_single___1__tmp13_[4]);
    XOR(MixColumn_single___1__tmp14_[5],MixColumn_single___1__tmp12_[5],MixColumn_single___1__tmp13_[5]);
    XOR(MixColumn_single___1__tmp14_[6],MixColumn_single___1__tmp12_[6],MixColumn_single___1__tmp13_[6]);
    XOR(MixColumn_single___1__tmp14_[7],MixColumn_single___1__tmp12_[7],MixColumn_single___1__tmp13_[7]);
    XOR(out__[((i__ * 32) + 8)],MixColumn_single___1__tmp14_[0],inp__[((i__ * 32) + 24)]);
    XOR(out__[((i__ * 32) + 9)],MixColumn_single___1__tmp14_[1],inp__[((i__ * 32) + 25)]);
    XOR(out__[((i__ * 32) + 10)],MixColumn_single___1__tmp14_[2],inp__[((i__ * 32) + 26)]);
    XOR(out__[((i__ * 32) + 11)],MixColumn_single___1__tmp14_[3],inp__[((i__ * 32) + 27)]);
    XOR(out__[((i__ * 32) + 12)],MixColumn_single___1__tmp14_[4],inp__[((i__ * 32) + 28)]);
    XOR(out__[((i__ * 32) + 13)],MixColumn_single___1__tmp14_[5],inp__[((i__ * 32) + 29)]);
    XOR(out__[((i__ * 32) + 14)],MixColumn_single___1__tmp14_[6],inp__[((i__ * 32) + 30)]);
    XOR(out__[((i__ * 32) + 15)],MixColumn_single___1__tmp14_[7],inp__[((i__ * 32) + 31)]);
    XOR(MixColumn_single___1__tmp15_[0],inp__[((i__ * 32) + 0)],inp__[((i__ * 32) + 8)]);
    XOR(MixColumn_single___1__tmp15_[1],inp__[((i__ * 32) + 1)],inp__[((i__ * 32) + 9)]);
    XOR(MixColumn_single___1__tmp15_[2],inp__[((i__ * 32) + 2)],inp__[((i__ * 32) + 10)]);
    XOR(MixColumn_single___1__tmp15_[3],inp__[((i__ * 32) + 3)],inp__[((i__ * 32) + 11)]);
    XOR(MixColumn_single___1__tmp15_[4],inp__[((i__ * 32) + 4)],inp__[((i__ * 32) + 12)]);
    XOR(MixColumn_single___1__tmp15_[5],inp__[((i__ * 32) + 5)],inp__[((i__ * 32) + 13)]);
    XOR(MixColumn_single___1__tmp15_[6],inp__[((i__ * 32) + 6)],inp__[((i__ * 32) + 14)]);
    XOR(MixColumn_single___1__tmp15_[7],inp__[((i__ * 32) + 7)],inp__[((i__ * 32) + 15)]);
    MixColumn_single___1_times2___3__tmp5_[0] = inp__[((i__ * 32) + 17)];
    MixColumn_single___1_times2___3__tmp5_[1] = inp__[((i__ * 32) + 18)];
    MixColumn_single___1_times2___3__tmp5_[2] = inp__[((i__ * 32) + 19)];
    MixColumn_single___1_times2___3__tmp5_[3] = inp__[((i__ * 32) + 20)];
    MixColumn_single___1_times2___3__tmp5_[4] = inp__[((i__ * 32) + 21)];
    MixColumn_single___1_times2___3__tmp5_[5] = inp__[((i__ * 32) + 22)];
    MixColumn_single___1_times2___3__tmp5_[6] = inp__[((i__ * 32) + 23)];
    MixColumn_single___1_times2___3__tmp5_[7] = SET_ALL_ONE();
    MixColumn_single___1__tmp16_[0] = MixColumn_single___1_times2___3__tmp5_[0];
    MixColumn_single___1__tmp16_[1] = MixColumn_single___1_times2___3__tmp5_[1];
    MixColumn_single___1__tmp16_[2] = MixColumn_single___1_times2___3__tmp5_[2];
    XOR(MixColumn_single___1__tmp16_[3],MixColumn_single___1_times2___3__tmp5_[3],inp__[((i__ * 32) + 16)]);
    XOR(MixColumn_single___1__tmp16_[4],MixColumn_single___1_times2___3__tmp5_[4],inp__[((i__ * 32) + 16)]);
    MixColumn_single___1__tmp16_[5] = MixColumn_single___1_times2___3__tmp5_[5];
    XOR(MixColumn_single___1__tmp16_[6],MixColumn_single___1_times2___3__tmp5_[6],inp__[((i__ * 32) + 16)]);
    XOR(MixColumn_single___1__tmp16_[7],MixColumn_single___1_times2___3__tmp5_[7],inp__[((i__ * 32) + 16)]);
    XOR(MixColumn_single___1__tmp17_[0],MixColumn_single___1__tmp15_[0],MixColumn_single___1__tmp16_[0]);
    XOR(MixColumn_single___1__tmp17_[1],MixColumn_single___1__tmp15_[1],MixColumn_single___1__tmp16_[1]);
    XOR(MixColumn_single___1__tmp17_[2],MixColumn_single___1__tmp15_[2],MixColumn_single___1__tmp16_[2]);
    XOR(MixColumn_single___1__tmp17_[3],MixColumn_single___1__tmp15_[3],MixColumn_single___1__tmp16_[3]);
    XOR(MixColumn_single___1__tmp17_[4],MixColumn_single___1__tmp15_[4],MixColumn_single___1__tmp16_[4]);
    XOR(MixColumn_single___1__tmp17_[5],MixColumn_single___1__tmp15_[5],MixColumn_single___1__tmp16_[5]);
    XOR(MixColumn_single___1__tmp17_[6],MixColumn_single___1__tmp15_[6],MixColumn_single___1__tmp16_[6]);
    XOR(MixColumn_single___1__tmp17_[7],MixColumn_single___1__tmp15_[7],MixColumn_single___1__tmp16_[7]);
    MixColumn_single___1_times3___3_times2___1__tmp5_[0] = inp__[((i__ * 32) + 25)];
    MixColumn_single___1_times3___3_times2___1__tmp5_[1] = inp__[((i__ * 32) + 26)];
    MixColumn_single___1_times3___3_times2___1__tmp5_[2] = inp__[((i__ * 32) + 27)];
    MixColumn_single___1_times3___3_times2___1__tmp5_[3] = inp__[((i__ * 32) + 28)];
    MixColumn_single___1_times3___3_times2___1__tmp5_[4] = inp__[((i__ * 32) + 29)];
    MixColumn_single___1_times3___3_times2___1__tmp5_[5] = inp__[((i__ * 32) + 30)];
    MixColumn_single___1_times3___3_times2___1__tmp5_[6] = inp__[((i__ * 32) + 31)];
    MixColumn_single___1_times3___3_times2___1__tmp5_[7] = SET_ALL_ONE();
    MixColumn_single___1_times3___3__tmp6_[0] = MixColumn_single___1_times3___3_times2___1__tmp5_[0];
    MixColumn_single___1_times3___3__tmp6_[1] = MixColumn_single___1_times3___3_times2___1__tmp5_[1];
    MixColumn_single___1_times3___3__tmp6_[2] = MixColumn_single___1_times3___3_times2___1__tmp5_[2];
    XOR(MixColumn_single___1_times3___3__tmp6_[3],MixColumn_single___1_times3___3_times2___1__tmp5_[3],inp__[((i__ * 32) + 24)]);
    XOR(MixColumn_single___1_times3___3__tmp6_[4],MixColumn_single___1_times3___3_times2___1__tmp5_[4],inp__[((i__ * 32) + 24)]);
    MixColumn_single___1_times3___3__tmp6_[5] = MixColumn_single___1_times3___3_times2___1__tmp5_[5];
    XOR(MixColumn_single___1_times3___3__tmp6_[6],MixColumn_single___1_times3___3_times2___1__tmp5_[6],inp__[((i__ * 32) + 24)]);
    XOR(MixColumn_single___1_times3___3__tmp6_[7],MixColumn_single___1_times3___3_times2___1__tmp5_[7],inp__[((i__ * 32) + 24)]);
    XOR(MixColumn_single___1__tmp18_[0],MixColumn_single___1_times3___3__tmp6_[0],inp__[((i__ * 32) + 24)]);
    XOR(MixColumn_single___1__tmp18_[1],MixColumn_single___1_times3___3__tmp6_[1],inp__[((i__ * 32) + 25)]);
    XOR(MixColumn_single___1__tmp18_[2],MixColumn_single___1_times3___3__tmp6_[2],inp__[((i__ * 32) + 26)]);
    XOR(MixColumn_single___1__tmp18_[3],MixColumn_single___1_times3___3__tmp6_[3],inp__[((i__ * 32) + 27)]);
    XOR(MixColumn_single___1__tmp18_[4],MixColumn_single___1_times3___3__tmp6_[4],inp__[((i__ * 32) + 28)]);
    XOR(MixColumn_single___1__tmp18_[5],MixColumn_single___1_times3___3__tmp6_[5],inp__[((i__ * 32) + 29)]);
    XOR(MixColumn_single___1__tmp18_[6],MixColumn_single___1_times3___3__tmp6_[6],inp__[((i__ * 32) + 30)]);
    XOR(MixColumn_single___1__tmp18_[7],MixColumn_single___1_times3___3__tmp6_[7],inp__[((i__ * 32) + 31)]);
    XOR(out__[((i__ * 32) + 16)],MixColumn_single___1__tmp17_[0],MixColumn_single___1__tmp18_[0]);
    XOR(out__[((i__ * 32) + 17)],MixColumn_single___1__tmp17_[1],MixColumn_single___1__tmp18_[1]);
    XOR(out__[((i__ * 32) + 18)],MixColumn_single___1__tmp17_[2],MixColumn_single___1__tmp18_[2]);
    XOR(out__[((i__ * 32) + 19)],MixColumn_single___1__tmp17_[3],MixColumn_single___1__tmp18_[3]);
    XOR(out__[((i__ * 32) + 20)],MixColumn_single___1__tmp17_[4],MixColumn_single___1__tmp18_[4]);
    XOR(out__[((i__ * 32) + 21)],MixColumn_single___1__tmp17_[5],MixColumn_single___1__tmp18_[5]);
    XOR(out__[((i__ * 32) + 22)],MixColumn_single___1__tmp17_[6],MixColumn_single___1__tmp18_[6]);
    XOR(out__[((i__ * 32) + 23)],MixColumn_single___1__tmp17_[7],MixColumn_single___1__tmp18_[7]);
    MixColumn_single___1_times3___4_times2___1__tmp5_[0] = inp__[((i__ * 32) + 1)];
    MixColumn_single___1_times3___4_times2___1__tmp5_[1] = inp__[((i__ * 32) + 2)];
    MixColumn_single___1_times3___4_times2___1__tmp5_[2] = inp__[((i__ * 32) + 3)];
    MixColumn_single___1_times3___4_times2___1__tmp5_[3] = inp__[((i__ * 32) + 4)];
    MixColumn_single___1_times3___4_times2___1__tmp5_[4] = inp__[((i__ * 32) + 5)];
    MixColumn_single___1_times3___4_times2___1__tmp5_[5] = inp__[((i__ * 32) + 6)];
    MixColumn_single___1_times3___4_times2___1__tmp5_[6] = inp__[((i__ * 32) + 7)];
    MixColumn_single___1_times3___4_times2___1__tmp5_[7] = SET_ALL_ONE();
    MixColumn_single___1_times3___4__tmp6_[0] = MixColumn_single___1_times3___4_times2___1__tmp5_[0];
    MixColumn_single___1_times3___4__tmp6_[1] = MixColumn_single___1_times3___4_times2___1__tmp5_[1];
    MixColumn_single___1_times3___4__tmp6_[2] = MixColumn_single___1_times3___4_times2___1__tmp5_[2];
    XOR(MixColumn_single___1_times3___4__tmp6_[3],MixColumn_single___1_times3___4_times2___1__tmp5_[3],inp__[((i__ * 32) + 0)]);
    XOR(MixColumn_single___1_times3___4__tmp6_[4],MixColumn_single___1_times3___4_times2___1__tmp5_[4],inp__[((i__ * 32) + 0)]);
    MixColumn_single___1_times3___4__tmp6_[5] = MixColumn_single___1_times3___4_times2___1__tmp5_[5];
    XOR(MixColumn_single___1_times3___4__tmp6_[6],MixColumn_single___1_times3___4_times2___1__tmp5_[6],inp__[((i__ * 32) + 0)]);
    XOR(MixColumn_single___1_times3___4__tmp6_[7],MixColumn_single___1_times3___4_times2___1__tmp5_[7],inp__[((i__ * 32) + 0)]);
    XOR(MixColumn_single___1__tmp19_[0],MixColumn_single___1_times3___4__tmp6_[0],inp__[((i__ * 32) + 0)]);
    XOR(MixColumn_single___1__tmp19_[1],MixColumn_single___1_times3___4__tmp6_[1],inp__[((i__ * 32) + 1)]);
    XOR(MixColumn_single___1__tmp19_[2],MixColumn_single___1_times3___4__tmp6_[2],inp__[((i__ * 32) + 2)]);
    XOR(MixColumn_single___1__tmp19_[3],MixColumn_single___1_times3___4__tmp6_[3],inp__[((i__ * 32) + 3)]);
    XOR(MixColumn_single___1__tmp19_[4],MixColumn_single___1_times3___4__tmp6_[4],inp__[((i__ * 32) + 4)]);
    XOR(MixColumn_single___1__tmp19_[5],MixColumn_single___1_times3___4__tmp6_[5],inp__[((i__ * 32) + 5)]);
    XOR(MixColumn_single___1__tmp19_[6],MixColumn_single___1_times3___4__tmp6_[6],inp__[((i__ * 32) + 6)]);
    XOR(MixColumn_single___1__tmp19_[7],MixColumn_single___1_times3___4__tmp6_[7],inp__[((i__ * 32) + 7)]);
    XOR(MixColumn_single___1__tmp20_[0],MixColumn_single___1__tmp19_[0],inp__[((i__ * 32) + 8)]);
    XOR(MixColumn_single___1__tmp20_[1],MixColumn_single___1__tmp19_[1],inp__[((i__ * 32) + 9)]);
    XOR(MixColumn_single___1__tmp20_[2],MixColumn_single___1__tmp19_[2],inp__[((i__ * 32) + 10)]);
    XOR(MixColumn_single___1__tmp20_[3],MixColumn_single___1__tmp19_[3],inp__[((i__ * 32) + 11)]);
    XOR(MixColumn_single___1__tmp20_[4],MixColumn_single___1__tmp19_[4],inp__[((i__ * 32) + 12)]);
    XOR(MixColumn_single___1__tmp20_[5],MixColumn_single___1__tmp19_[5],inp__[((i__ * 32) + 13)]);
    XOR(MixColumn_single___1__tmp20_[6],MixColumn_single___1__tmp19_[6],inp__[((i__ * 32) + 14)]);
    XOR(MixColumn_single___1__tmp20_[7],MixColumn_single___1__tmp19_[7],inp__[((i__ * 32) + 15)]);
    XOR(MixColumn_single___1__tmp21_[0],MixColumn_single___1__tmp20_[0],inp__[((i__ * 32) + 16)]);
    XOR(MixColumn_single___1__tmp21_[1],MixColumn_single___1__tmp20_[1],inp__[((i__ * 32) + 17)]);
    XOR(MixColumn_single___1__tmp21_[2],MixColumn_single___1__tmp20_[2],inp__[((i__ * 32) + 18)]);
    XOR(MixColumn_single___1__tmp21_[3],MixColumn_single___1__tmp20_[3],inp__[((i__ * 32) + 19)]);
    XOR(MixColumn_single___1__tmp21_[4],MixColumn_single___1__tmp20_[4],inp__[((i__ * 32) + 20)]);
    XOR(MixColumn_single___1__tmp21_[5],MixColumn_single___1__tmp20_[5],inp__[((i__ * 32) + 21)]);
    XOR(MixColumn_single___1__tmp21_[6],MixColumn_single___1__tmp20_[6],inp__[((i__ * 32) + 22)]);
    XOR(MixColumn_single___1__tmp21_[7],MixColumn_single___1__tmp20_[7],inp__[((i__ * 32) + 23)]);
    MixColumn_single___1_times2___4__tmp5_[0] = inp__[((i__ * 32) + 25)];
    MixColumn_single___1_times2___4__tmp5_[1] = inp__[((i__ * 32) + 26)];
    MixColumn_single___1_times2___4__tmp5_[2] = inp__[((i__ * 32) + 27)];
    MixColumn_single___1_times2___4__tmp5_[3] = inp__[((i__ * 32) + 28)];
    MixColumn_single___1_times2___4__tmp5_[4] = inp__[((i__ * 32) + 29)];
    MixColumn_single___1_times2___4__tmp5_[5] = inp__[((i__ * 32) + 30)];
    MixColumn_single___1_times2___4__tmp5_[6] = inp__[((i__ * 32) + 31)];
    MixColumn_single___1_times2___4__tmp5_[7] = SET_ALL_ONE();
    MixColumn_single___1__tmp22_[0] = MixColumn_single___1_times2___4__tmp5_[0];
    MixColumn_single___1__tmp22_[1] = MixColumn_single___1_times2___4__tmp5_[1];
    MixColumn_single___1__tmp22_[2] = MixColumn_single___1_times2___4__tmp5_[2];
    XOR(MixColumn_single___1__tmp22_[3],MixColumn_single___1_times2___4__tmp5_[3],inp__[((i__ * 32) + 24)]);
    XOR(MixColumn_single___1__tmp22_[4],MixColumn_single___1_times2___4__tmp5_[4],inp__[((i__ * 32) + 24)]);
    MixColumn_single___1__tmp22_[5] = MixColumn_single___1_times2___4__tmp5_[5];
    XOR(MixColumn_single___1__tmp22_[6],MixColumn_single___1_times2___4__tmp5_[6],inp__[((i__ * 32) + 24)]);
    XOR(MixColumn_single___1__tmp22_[7],MixColumn_single___1_times2___4__tmp5_[7],inp__[((i__ * 32) + 24)]);
    XOR(out__[((i__ * 32) + 24)],MixColumn_single___1__tmp21_[0],MixColumn_single___1__tmp22_[0]);
    XOR(out__[((i__ * 32) + 25)],MixColumn_single___1__tmp21_[1],MixColumn_single___1__tmp22_[1]);
    XOR(out__[((i__ * 32) + 26)],MixColumn_single___1__tmp21_[2],MixColumn_single___1__tmp22_[2]);
    XOR(out__[((i__ * 32) + 27)],MixColumn_single___1__tmp21_[3],MixColumn_single___1__tmp22_[3]);
    XOR(out__[((i__ * 32) + 28)],MixColumn_single___1__tmp21_[4],MixColumn_single___1__tmp22_[4]);
    XOR(out__[((i__ * 32) + 29)],MixColumn_single___1__tmp21_[5],MixColumn_single___1__tmp22_[5]);
    XOR(out__[((i__ * 32) + 30)],MixColumn_single___1__tmp21_[6],MixColumn_single___1__tmp22_[6]);
    XOR(out__[((i__ * 32) + 31)],MixColumn_single___1__tmp21_[7],MixColumn_single___1__tmp22_[7]);
  }

}

static void AddRoundKey__ (/*inputs*/ DATATYPE a__[128],DATATYPE b__[128], /*outputs*/ DATATYPE c__[128]) {
  
  // Variables declaration
  ;

  // Instructions (body)
  for (int i__ = 0; i__ <= 127; i__++) {
    XOR(c__[i__],a__[i__],b__[i__]);
  }

}

static void round_compact (/*inputs*/ DATATYPE plain__[128],DATATYPE key__[128], /*outputs*/ DATATYPE cipher__[128]) {
  
  // Variables declaration
  DATATYPE _tmp23_[128];
  DATATYPE _tmp24_[128];
  DATATYPE _tmp25_[128];

  // Instructions (body)
  SubBytes__(plain__,_tmp23_);
  ShiftRows__(_tmp23_,_tmp24_);
  MixColumn__(_tmp24_,_tmp25_);
  AddRoundKey__(_tmp25_,key__,cipher__);

}

/* main function */
static void lastround_compact (/*inputs*/ DATATYPE plain__[128],DATATYPE key__[128], /*outputs*/ DATATYPE cipher__[128]) {
  
  // Variables declaration
  DATATYPE _tmp26_[128];
  DATATYPE _tmp27_[128];

  // Instructions (body)
  SubBytes__(plain__,_tmp26_);
  ShiftRows__(_tmp26_,_tmp27_);
  AddRoundKey__(_tmp27_,key__,cipher__);

}


/* **************************************************************** */
/*                            Usuba source                          */
/*                                                                  */
/*

_no_inline table SubBytes_single(input :  u1x8 :: base)
  returns output :  u1x8 :: base
{
  99, 124, 119, 123, 242, 107, 111, 197, 48, 1, 103, 43, 254, 215, 171, 118, 202, 130, 201, 125, 250, 89, 71, 240, 173, 212, 162, 175, 156, 164, 114, 192, 183, 253, 147, 38, 54, 63, 247, 204, 52, 165, 229, 241, 113, 216, 49, 21, 4, 199, 35, 195, 24, 150, 5, 154, 7, 18, 128, 226, 235, 39, 178, 117, 9, 131, 44, 26, 27, 110, 90, 160, 82, 59, 214, 179, 41, 227, 47, 132, 83, 209, 0, 237, 32, 252, 177, 91, 106, 203, 190, 57, 74, 76, 88, 207, 208, 239, 170, 251, 67, 77, 51, 133, 69, 249, 2, 127, 80, 60, 159, 168, 81, 163, 64, 143, 146, 157, 56, 245, 188, 182, 218, 33, 16, 255, 243, 210, 205, 12, 19, 236, 95, 151, 68, 23, 196, 167, 126, 61, 100, 93, 25, 115, 96, 129, 79, 220, 34, 42, 144, 136, 70, 238, 184, 20, 222, 94, 11, 219, 224, 50, 58, 10, 73, 6, 36, 92, 194, 211, 172, 98, 145, 149, 228, 121, 231, 200, 55, 109, 141, 213, 78, 169, 108, 86, 244, 234, 101, 122, 174, 8, 186, 120, 37, 46, 28, 166, 180, 198, 232, 221, 116, 31, 75, 189, 139, 138, 112, 62, 181, 102, 72, 3, 246, 14, 97, 53, 87, 185, 134, 193, 29, 158, 225, 248, 152, 17, 105, 217, 142, 148, 155, 30, 135, 233, 206, 85, 40, 223, 140, 161, 137, 13, 191, 230, 66, 104, 65, 153, 45, 15, 176, 84, 187, 22
}


_no_inline node SubBytes(inputSB :  u1x8[16] :: base)
  returns out :  u1x8[16] :: base
vars

let
  _no_unroll forall i in [0,15] {
    (out[i]) = SubBytes_single(inputSB[i])
  }
tel

_no_inline node ShiftRows(inputSR :  u1x8[16] :: base)
  returns output :  bool[128] :: base
vars

let
  (output) = inputSR[0,5,10,15,4,9,14,3,8,13,2,7,12,1,6,11]
tel

 node times2(i :  bool[8] :: base)
  returns o :  bool[8] :: base
vars

let
  (o) = ((i << 1) ^ (0,0,0,i[0],i[0],0,i[0],i[0]))
tel

 node times3(i :  bool[8] :: base)
  returns o :  bool[8] :: base
vars

let
  (o) = (times2(i) ^ i)
tel

 node MixColumn_single(inp :  u1x8[4] :: base)
  returns out :  u1x8[4] :: base
vars

let
  (out[0]) = (((times2(inp[0]) ^ times3(inp[1])) ^ inp[2]) ^ inp[3]);
  (out[1]) = (((inp[0] ^ times2(inp[1])) ^ times3(inp[2])) ^ inp[3]);
  (out[2]) = (((inp[0] ^ inp[1]) ^ times2(inp[2])) ^ times3(inp[3]));
  (out[3]) = (((times3(inp[0]) ^ inp[1]) ^ inp[2]) ^ times2(inp[3]))
tel

_no_inline node MixColumn(inp :  u1x32[4] :: base)
  returns out :  u1x32[4] :: base
vars

let
  _no_unroll forall i in [0,3] {
    (out[i]) = MixColumn_single(inp[i])
  }
tel

_no_inline node AddRoundKey(a :  u1x1[128] :: base,b :  u1x1[128] :: base)
  returns c :  u1x1[128] :: base
vars

let
  _no_unroll forall i in [0,127] {
    (c[i]) = (a[i] ^ b[i])
  }
tel

_no_inline node round(plain :  u1x128 :: base,key :  u1x128 :: base)
  returns cipher :  u1x128 :: base
vars

let
  (cipher) = AddRoundKey(MixColumn(ShiftRows(SubBytes(plain))),key)
tel

_no_inline node lastround(plain :  u1x128 :: base,key :  u1x128 :: base)
  returns cipher :  u1x128 :: base
vars

let
  (cipher) = AddRoundKey(ShiftRows(SubBytes(plain)),key)
tel

*/
 
